# Site settings
title: Nick's Blog
email: weichangying@msn.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://atchina.github.io" # the base hostname & protocol for your site
github_username:  AtChina
permalink: /:title
production_url : http://atchina.github.io
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
highlighter: pygments

# defaults settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nick"
      categories: "UnDefined"

