# Site settings
title: Nick's Blog
author: Nick
email: weichangying@msn.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://atchina.github.io"
github_username:  AtChina
permalink: /:categories/:title
production_url : http://atchina.github.io
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
highlighter: pygments

# defaults settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nick"
      comments: true
  -
    scope:
      path: "生活随笔"
    values:
      categories: "生活随笔"     
  -
    scope:
      path: "业务知识"
    values:
      categories: "业务知识"             
  -
    scope:
      path: "开发笔记"
    values:
      categories: "开发笔记"                       
  -
    scope:
      path: "软件圈子"
    values:
      categories: "软件圈子"
  -
    scope:
      path: "技术研究"
    values:
      categories: "技术研究"
  -
    scope:
      path: "框架工具"
    values:
      categories: "框架工具"