# Site settings
title: Nick's Blog
author: Nick
email: weichangying@msn.com
description: "Share only to make the world a better place"
baseurl: "/"
url: "http://atchina.me/"
github_username: AtChina
permalink: "/:categories/:title"
production_url: "http://atchina.me/"
paginate: 5
paginate_path: "page:num"

#comments settings
comments:
  provider: duoshuo
  duoshuo: 
    short_name: atchina

# Build settings
markdown: kramdown
highlighter: pygments

# defaults settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nick"
      comments: true
  -
    scope:
      path: "生活随笔"
    values:
      categories: "生活随笔"     
  -
    scope:
      path: "业务知识"
    values:
      categories: "业务知识"             
  -
    scope:
      path: "开发笔记"
    values:
      categories: "开发笔记"                       
  -
    scope:
      path: "软件圈子"
    values:
      categories: "软件圈子"
  -
    scope:
      path: "技术研究"
    values:
      categories: "技术研究"
  -
    scope:
      path: "框架工具"
    values:
      categories: "框架工具"     
